# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/httprunnerdemo.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLongin(HttpRunner):
    config = (
        Config("testcase description") \
            .base_url("https://api2.${host}") \
            .verify(False) \
            .variables(**{
            "data_unique_id": "63743813-8230-4b9c-bb5a-f42416b1bbbf",
            "csrf_token": "bd41907d-ce86-41a5-a207-7b3d76aba3ab",
            "host": "${get_test_host()}",
            "phone": "13966566216",
            "password": "chen123789",
        })
            .export("Jwt_Token", "user_persistence", "userId")
    )

    teststeps = [
        Step(
            RunRequest("/api/login/submit")
                .with_variables(**{
                "remember": "true"
            })
                .post("https://${host}/api/login/submit")
                .with_headers(
                **{
                    "content-length": "51",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "use-redesign": "1",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "${csrf_token}",
                    "data-unique-id": "59cf2860-3d3d-11eb-bad8-7f7b66d6f90f",
                    "_gat": "1",
                }
            )
                .with_data(
                {"phone": "${phone}", "password": "${password}", "remember": "${remember}"}
            )
                .teardown_hook("${sleep(2)}")
                .extract()
                .with_jmespath('cookies."Jwt-Token"', "Jwt_Token")
                .with_jmespath('cookies.user_persistence', "user_persistence")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
                .assert_equal("body.data.next", "/list")
        ),
        Step(
            RunRequest("/app")
                .get("https://${host}/app")
                .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "use-redesign": "1",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "${csrf_token}",
                    "data-unique-id": "59cf2860-3d3d-11eb-bad8-7f7b66d6f90f",
                    "_gat": "1",
                    "Jwt-Token": "${Jwt_Token}",
                    "user_persistence": "${user_persistence}",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/")
                .get("/v3/")
                .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
                    "accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "no-cors",
                    "sec-fetch-dest": "image",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "use-redesign": "1",
                    "_gat": "1",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 17)
                .assert_equal("body.msg", "illegal request")
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
                .post("/v3/api/message/get_message_unread")
                .with_headers(
                **{
                    "content-length": "10",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${Jwt_Token}",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
                    "data-unique-id": "59cf2860-3d3d-11eb-bad8-7f7b66d6f90f",
                    "x-request-id": "${get_random_request_id()}",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_json({"page": 1})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
                .post("/v3/api/user/profile")
                .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${Jwt_Token}",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
                    "data-unique-id": "59cf2860-3d3d-11eb-bad8-7f7b66d6f90f",
                    "x-request-id": "${get_random_request_id()}",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_data("")
                .extract()
                .with_jmespath("body.data.id", "userId")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_greater_than("body.data.vipEndDate", "20201227")
        ),

    ]


if __name__ == "__main__":
    TestCaseMubuLongin().test_start()
