# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/addpeople.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.work_weixin.base_config import Base

base = Base()
names = base.get_name_and_sex()
username = names[0]
gender = names[1]

class TestCaseAddContacts(HttpRunner):

    config = Config("添加成员").verify(False)

    teststeps = [
        Step(
            RunRequest("添加成员")
            .post("https://work.weixin.qq.com/wework_admin/contacts/saveMember")
            .with_params(
                **{
                    "method": "create",
                    "partyid": "1688850882286378",
                    "lang": "zh_CN",
                    "f": "json",
                }
            )
            .with_headers(
                **{
                    "referer": "https://work.weixin.qq.com/wework_admin/frame",
                }
            )
            .with_cookies(
                **{
                    "wwrtx.sid": base.wwrtx_sid,
                }
            )
            .with_data(
                {
                    "__member": "true",
                    "party_list[]": "1688850882286378",
                    "country_code": "86",
                    "avatar": "",
                    "username": username,
                    "english_name": "小"+username,
                    "acctid": "${get_random_number(10)}",
                    "gender": gender,
                    "mobile": "${get_phone_number()}",
                    "ext_tel": "",
                    "alias": "",
                    "xcx_corp_address": "",
                    "mainparty_id": "",
                    "partyid": "1688850882286378",
                    "party_check": "0",
                    "position": "",
                    "identity_stat": "0",
                    "extern_position": "",
                    "sendInvite": "on",
                    "hide_mobile": "false",
                    "extern_position_info[b_syn_inner_position]": "true",
                    "extern_position_info[extern_position]": "",
                    "active_biz": "false",
                    "switch_active_biz": "false",
                    "disable_biz": "false",
                    "switch_disable_biz": "false",
                    "bind_stat": "0",
                    "external_corp_info": "",
                    "ignore_abnormal_mobile": "false",
                    "_d2st": "a5266798",
                }
            )
            .extract()
            .with_jmespath("body.data.vid","uid")
            .validate()
            .assert_equal("status_code", 200)
            # .assert_not_null("body.data.vid")
        ),
    ]


if __name__ == "__main__":
    TestCaseAddContacts().test_start()
    # print(name)


