# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/delete_contacts.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.work_weixin.add_contacts_test import TestCaseAddContacts as AddContacts
from testcases.work_weixin.base_config import Base

base = Base()


class TestCaseDeleteContacts(HttpRunner):
    config = Config("删除成员").verify(False)

    teststeps = [
        Step(
            RunTestCase("add_contacts")
                .call(AddContacts)
                .export("uid")
        ),
        Step(
            RunRequest("删除成员")
                .post("https://work.weixin.qq.com/wework_admin/NewDelMemberBatch")
                .with_headers(
                **{
                    "referer": "https://work.weixin.qq.com/wework_admin/frame",
                }
            )
                .with_cookies(
                **{
                    "wwrtx.sid": base.wwrtx_sid,
                }
            )
                .with_data(
                {
                    "vids[]": "$uid",
                    "depart_id": "1688850882286378",
                    # "_d2st": "a1765935",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.data.pairs[0].vid", "$uid")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeleteContacts().test_start()
